version: '3.9'
services:
  test-db:
    image: postgres
    container_name: test-db
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    cpu_count: 2
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
